"""election, voter, board tables

Revision ID: 2a7f76a16376
Revises: 
Create Date: 2018-05-27 16:05:44.282253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7f76a16376'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election',
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('search_name', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('questions', sa.PickleType(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('public_key', sa.PickleType(), nullable=True),
    sa.Column('secret_key', sa.PickleType(), nullable=True),
    sa.Column('election_dict', sa.PickleType(), nullable=True),
    sa.Column('result', sa.PickleType(), nullable=True),
    sa.Column('proof', sa.PickleType(), nullable=True),
    sa.Column('voters', sa.PickleType(), nullable=True),
    sa.Column('bulletin_list', sa.PickleType(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('election_id')
    )
    op.create_table('voter',
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('e_mail', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('voter_identifier', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['election.election_id'], ),
    sa.PrimaryKeyConstraint('voter_id')
    )
    op.create_table('board',
    sa.Column('ballot_id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('voter_identifier', sa.String(length=128), nullable=True),
    sa.Column('ballot_dict', sa.PickleType(), nullable=True),
    sa.Column('ballot_hash', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['election.election_id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.voter_id'], ),
    sa.PrimaryKeyConstraint('ballot_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    op.drop_table('voter')
    op.drop_table('election')
    # ### end Alembic commands ###
